Repository satyrnidae/wolf-armor-and-storage-legacy, pull requests merged in 2022-01, with the labels that each got.

#180 French Translation
  src/main/resources/assets/wolfarmor/lang/fr_fr.lang
Labels: 1.12, translation

#185 👷🏼‍♀️Update build.gradle
  build.gradle
  gradle.properties
Labels: 1.12, ci build

#187 🔀 Merge Bugs/1.12/167 error code 0
  .github/ISSUE_TEMPLATE/1-bug.md
  .github/ISSUE_TEMPLATE/2-compatiblity.md
  .github/ISSUE_TEMPLATE/3-feature.md
  .github/ISSUE_TEMPLATE/99-other.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/compatiblity-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: 1.12, ci build, high priority

#188 💚 Exclude Sponge mixin package from SignJar operation.
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: 1.12

#191 Working/1.12/remove obfuscation helper
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  gradle.properties
  src/main/java/dev/satyrn/wolfarmor/client/event/RenderEventHandler.java
  src/main/java/dev/satyrn/wolfarmor/mixin/accessors/RenderAccessor.java
  src/main/resources/mixins.wolfarmor.core.json
Labels: bug, 1.12

#193 Features/1.12/mo bends compatibility
  build.gradle
  gradle.properties
  src/main/java/dev/satyrn/wolfarmor/WolfArmorMod.java
  src/main/java/dev/satyrn/wolfarmor/api/common/IProxy.java
  src/main/java/dev/satyrn/wolfarmor/api/compatibility/Compatibility.java
  src/main/java/dev/satyrn/wolfarmor/api/compatibility/CompatibilityProvider.java
  src/main/java/dev/satyrn/wolfarmor/client/ClientProxy.java
  src/main/java/dev/satyrn/wolfarmor/client/model/ModelWolfBackpack.java
  src/main/java/dev/satyrn/wolfarmor/client/renderer/entity/layer/LayerWolfArmor.java
  src/main/java/dev/satyrn/wolfarmor/client/renderer/entity/layer/LayerWolfBackpack.java
  src/main/java/dev/satyrn/wolfarmor/common/CommonProxy.java
  src/main/java/dev/satyrn/wolfarmor/compatibility/ebwizardry/WizardryProvider.java
  src/main/java/dev/satyrn/wolfarmor/compatibility/mobends/MoBendsProvider.java
  src/main/java/dev/satyrn/wolfarmor/compatibility/mobends/WolfArmorAndStorageAddon.java
  src/main/java/dev/satyrn/wolfarmor/compatibility/mobends/mutators/ArmoredWolfMutator.java
  src/main/java/dev/satyrn/wolfarmor/compatibility/sophisticatedwolves/SophisticatedWolvesProvider.java
Labels: bug, 1.12, high priority
